---
title: "Unmasking Variables: A Descriptive Analysis of Gun Violence Correlates in New York"
output: 
  html_document:
    theme: flatly
---

*welcome image*

### **About**

Gun violence is a persistent public health crisis in the United States. In New York City, for example, we had the (Midtown Manhattan mass shooting)[https://www.cnn.com/2025/08/03/us/manhattan-shooting-timeline-911-calls] in July 2025. It showed us that even our busiest, most protected neighborhoods are impacted by gun violence. We set out to perform a descriptive exploration of socioeconomic, geographic, and temporal factors that are potentially positively or negatively associated with firearm shootings in Manhattan, NYC.

### **Map of Manhattan Shootings**

Based on data from 2006-September 2025. Hover over each point to see [whatever it shows].

*map of shootings*

### **Our Data Sources**

#### *Main Data*

[info on shooting data]

#### *Other Sources*

[info on other data]

### **The Team**

- Ainsel Levitskaia-Collins (HL2710)
- Alissa Shams Orchi (AO2965)
- Kino Watanabe (KW3180)
- Miho Kawanami (MK4996)
- Te-Hsuan Huang (TH3147)

### **The Screencast**

[embed or link to unlisted video]